theme: jekyll-theme-slate
title: 窗外蟋蟀
SEOTitle: 窗外蟋蟀的博客 | 贵阳 Blog
header-img: img/home-bg-hill.jpg
email: keysaim@gmail.com
description: "描述"
keyword: "窗外蟋蟀, gyfeng1003"
url: "https://gyfeng1003.github.io"
baseurl: ""
